# ACS TIME SERIES BROAD SUMMARIES

In [1]:
import os, csv, pandas as pd

In [2]:
sumlev_names={'010':'US','020':'Region','030':'Division','040':'State','050':'County',
             '060':'County Subdiv','140':'Tract','150':'Blk Group','160':'Place','170':'Cons City',
              '250':'Tribal Area','251':'Tribal Subdiv','256':'Tribal Tract','258':'Tribal Blk Group', 
              '310':'CBSA','400':'Urban Area','500':'Cong Dist','795':'PUMA','860':'ZCTA'}

In [3]:
tab_names={}
tab_file=os.path.join('metatables','acs_tables.csv')
with open(tab_file, 'r', newline='') as csvfile:
    reader = csv.DictReader(csvfile)
    for row in reader:
        tab_names[row['tab_id'].lower()]=row['tab_lbl'].title()
        
droptabs=['b09001','b09020','b98001','b98003']
for k in [k for k in tab_names if k in droptabs]: del tab_names[k]
len(tab_names)

25

In [4]:
var_names={}
var_file=os.path.join('metatables','acs_variables.csv')
with open(var_file, 'r', newline='') as csvfile:
    reader = csv.DictReader(csvfile)
    for row in reader:
        var_names[row['var_id'].lower()]=row['var_lbl'].title()
        
dropvars=['b09001_001','b09020_001','b98001_002','b98003_001']
for k in [k for k in var_names if k in dropvars]: del var_names[k]

var_names_short={}
for k,v in var_names.items():
    short_label=v.split('%')[-2:]
    var_names_short[k]=' - '.join(short_label)    
len(var_names)

317

# Significant Difference

In [5]:
sd_total_file=os.path.join('sumdata','sigdif_total_grand.tsv')
sd_total=pd.read_csv(sd_total_file,delimiter='\t')
sd_total

  sig_dif  sig_dif_count  percent
0   False       96258224     89.5
1    True       10931539     10.2
2     NaN         306411      0.3

## General Share of Records

### Share by Summary Level

In [6]:
sd_geoshare_file=os.path.join('sumdata','sigdif_share_geo.tsv')
sd_geoshare=pd.read_csv(sd_geoshare_file,delimiter='\t',dtype={'sumlevel':str})
sd_geoshare['sumlevel']=sd_geoshare['sumlevel'].map(sumlev_names)
sd_geoshare.sort_values(by=['percent','sig_dif_count'],ascending=False)

            sumlevel  sig_dif_count  percent
7          Blk Group       50154072     46.7
6              Tract       22755378     21.2
5      County Subdiv       11292096     10.5
18              ZCTA       10234080      9.5
8              Place        9118590      8.5
15        Urban Area        1109928      1.0
4             County         994980      0.9
17              PUMA         734802      0.7
14              CBSA         245964      0.2
10       Tribal Area         214137      0.2
13  Tribal Blk Group         208620      0.2
12      Tribal Tract         148629      0.1
11     Tribal Subdiv         148320      0.1
16         Cong Dist         113712      0.1
3              State          16068      0.0
2           Division           2781      0.0
9          Cons City           2472      0.0
1             Region           1236      0.0
0                 US            309      0.0

### Share by Table

In [7]:
sd_tabshare_file=os.path.join('sumdata','sigdif_share_tab.tsv')
sd_tabshare=pd.read_csv(sd_tabshare_file,delimiter='\t')
sd_tabshare['label']=sd_tabshare['table'].map(tab_names)
sd_tabshare.sort_values(by='percent',ascending=False)

,table,sig_dif_count,percent,label
0,b01001,19883563,18.0,Sex By Age
10,b15002,14202545,12.9,Sex By Educational Attainment For The Populati...
24,c24030,11767823,10.6,Sex By Industry For The Civilian Employed Popu...
18,b25063,9738888,8.8,Gross Rent
3,b03002,8521527,7.7,Hispanic Or Latino Origin By Race
11,b19001,6898379,6.2,Household Income In The Past 12 Months (In 201...
20,b25070,4463657,4.0,Gross Rent As A Percentage Of Household Income...
2,b02001,4057870,3.7,Race
7,b11001,3652083,3.3,Household Type (Including Living Alone)
5,b07204,3513062,3.2,Geographical Mobility In The Past Year For Cur...
8,b13002,3513062,3.2,Women 15 To 50 Years Who Had A Birth In The Pa...
23,c17002,3246296,2.9,Ratio Of Income To Poverty Level In The Past 1...
6,b08006,3143266,2.8,Sex Of Workers By Means Of Transportation To Work
14,b23025,2840509,2.6,Employment Status For The Population 16 Years ...
4,b05002,2773470,2.5,Place Of Birth By Nativity And Citizenship Status
9,b14001,1848980,1.7,School Enrollment By Level Of School For The P...
15,b25002,1217361,1.1,Occupancy Status
16,b25003,1217361,1.1,Tenure
17,b25010,1217361,1.1,Average Household Size Of Occupied Housing Uni...
1,b01002,1217361,1.1,Median Age By Sex
19,b25064,405787,0.4,Median Gross Rent (Dollars)
21,b25077,405787,0.4,Median Value (Dollars)
12,b19013,405787,0.4,Median Household Income In The Past 12 Months ...
13,b19083,184898,0.2,Gini Index Of Income Inequality
22,b26001,184898,0.2,Group Quarters Population

## Significant Difference by Summary Level

In [8]:
sd_pctgeo_file=os.path.join('sumdata','sigdif_pct_geo.tsv')
sd_pctgeo=pd.read_csv(sd_pctgeo_file,delimiter='\t',dtype={'sumlevel':str})
sd_pctgeo['sumlevel']=sd_pctgeo['sumlevel'].map(sumlev_names)
sd_pctgeo.loc[sd_pctgeo['sig_dif']==True].sort_values(by='percent',ascending=False)

            sumlevel sig_dif  sig_dif_count  percent
1                 US    True            290     93.9
3             Region    True           1138     92.1
5           Division    True           2465     88.6
7              State    True          11647     72.5
45         Cong Dist    True          61837     54.4
25         Cons City    True            983     39.8
48              PUMA    True         260775     35.5
39              CBSA    True          86636     35.2
10            County    True         279300     28.1
42        Urban Area    True         193420     17.4
16             Tract    True        2822174     12.4
51              ZCTA    True        1215977     11.9
13     County Subdiv    True        1131118     10.0
33      Tribal Tract    True          14777      9.9
22             Place    True         847449      9.3
36  Tribal Blk Group    True          19238      9.2
27       Tribal Area    True          18013      8.4
30     Tribal Subdiv    True          11988      8.1
19         Blk Group    True        3952314      7.9

## Significant Difference By Table

In [9]:
sd_pcttab_file=os.path.join('sumdata','sigdif_pct_tab.tsv')
sd_pcttab=pd.read_csv(sd_pcttab_file,delimiter='\t')
sd_pcttab['label']=sd_pcttab['table'].map(tab_names)
sd_pcttab.loc[sd_pcttab['sig_dif']==True].sort_values(by='percent',ascending=False)

,table,sig_dif,sig_dif_count,percent,label
52,b25077,True,122125,30.1,Median Value (Dollars)
38,b25002,True,222413,18.3,Occupancy Status
40,b25003,True,215219,17.7,Tenure
36,b23025,True,501004,17.6,Employment Status For The Population 16 Years ...
24,b14001,True,314233,17.0,School Enrollment By Level Of School For The P...
47,b25064,True,67998,16.8,Median Gross Rent (Dollars)
33,b19083,True,30812,16.7,Gini Index Of Income Inequality
42,b25010,True,195951,16.1,Average Household Size Of Occupied Housing Uni...
30,b19013,True,64315,15.8,Median Household Income In The Past 12 Months ...
4,b01002,True,186897,15.4,Median Age By Sex
19,b11001,True,524814,14.4,Household Type (Including Living Alone)
12,b05002,True,386998,14.0,Place Of Birth By Nativity And Citizenship Status
57,c17002,True,440367,13.6,Ratio Of Income To Poverty Level In The Past 1...
28,b19001,True,850261,12.3,Household Income In The Past 12 Months (In 201...
1,b01001,True,2262353,11.4,Sex By Age
17,b08006,True,339638,10.8,Sex Of Workers By Means Of Transportation To Work
7,b02001,True,406030,10.0,Race
21,b13002,True,346752,9.9,Women 15 To 50 Years Who Had A Birth In The Pa...
14,b07204,True,336426,9.6,Geographical Mobility In The Past Year For Cur...
59,c24030,True,1035052,8.8,Sex By Industry For The Civilian Employed Popu...
26,b15002,True,1162736,8.2,Sex By Educational Attainment For The Populati...
50,b25070,True,339409,7.6,Gross Rent As A Percentage Of Household Income...
9,b03002,True,626660,7.4,Hispanic Or Latino Origin By Race
45,b25063,True,568913,5.8,Gross Rent
55,b26001,True,5364,2.9,Group Quarters Population

## Significant Difference by Type of Variable

In [10]:
sd_pctvtype_file=os.path.join('sumdata','sigdif_pct_vtype.tsv')
sd_pctvtype=pd.read_csv(sd_pctvtype_file,delimiter='\t')
sd_pctvtype

    vartype sig_dif  sig_dif_count  percent
0  estimate   False       90658159     90.4
1  estimate    True        9549754      9.5
2  estimate     NaN          92068      0.1
3   summary   False        2959654     77.1
4   summary    True         668098     17.4
5   summary     NaN         209229      5.5
6  universe   False        2640411     78.6
7  universe    True         713687     21.2
8  universe     NaN           5114      0.2

## Significant Difference by Variable

In [11]:
sd_pctvar_file=os.path.join('sumdata','sigdif_pct_var.tsv')
sd_pctvar=pd.read_csv(sd_pctvar_file,delimiter='\t')
sd_pctvar['label']=sd_pctvar['variable'].map(var_names_short)
sd_pctvar.loc[sd_pctvar['sig_dif']==True].sort_values(by='percent',ascending=False).head(n=20)

,variable,sig_dif,sig_dif_count,percent,label
174,b05002_001,True,55882,30.2,Total Population - Total
608,b25077_001,True,122125,30.1,Owner-Occupied Housing Units - Median Value (...
204,b07204_001,True,52930,28.6,Population 1 Year And Over In The United Stat...
370,b14001_001,True,51356,27.8,Population 3 Years And Over - Total
388,b14001_010,True,48756,26.4,Total - Not Enrolled In School
176,b05002_002,True,48011,26.0,Total - Native
261,b08006_001,True,46680,25.2,Workers 16 Years And Over - Total
508,b23025_005,True,100734,24.8,Civilian Labor Force - Unemployed
207,b07204_002,True,44256,23.9,Total - Same House 1 Year Ago
263,b08006_002,True,43069,23.3,Total - Car Truck Or Van
1,b01001_001,True,93616,23.1,Total Population - Total
130,b03002_001,True,93616,23.1,Total Population - Total
110,b02001_001,True,93616,23.1,Total Population - Total
265,b08006_003,True,42762,23.1,Car Truck Or Van - Drove Alone
613,c17002_001,True,89192,22.0,Population For Whom Poverty Status Is Determi...
390,b15002_001,True,86710,21.4,Population 25 Years And Over - Total
627,c17002_008,True,86360,21.3,Total - 2.00 And Over
500,b23025_001,True,86565,21.3,Population 16 Years And Over - Total
132,b03002_002,True,85017,21.0,Total - Not Hispanic Or Latino
112,b02001_002,True,84457,20.8,Total - White Alone

In [12]:
sd_pctvar.loc[sd_pctvar['sig_dif']==True].sort_values(by=['percent','sig_dif_count'],ascending=False).tail(n=20)

,variable,sig_dif,sig_dif_count,percent,label
334,b13002_008,True,2476,1.3,Unmarried (Never Married Widowed And Divorced)...
543,b25063_005,True,4922,1.2,With Cash Rent - $150 To $199
510,b23025_006,True,4289,1.1,In Labor Force - Armed Forces
145,b03002_008,True,3736,0.9,Not Hispanic Or Latino - Some Other Race Alone
120,b02001_006,True,3432,0.8,Total - Native Hawaiian And Other Pacific Isla...
143,b03002_007,True,3258,0.8,Not Hispanic Or Latino - Native Hawaiian And O...
160,b03002_015,True,3130,0.8,Hispanic Or Latino - American Indian And Alask...
340,b13002_010,True,1462,0.8,Unmarried (Never Married Widowed And Divorced)...
194,b05002_011,True,1250,0.7,Born Outside The United States - U.S. Island A...
349,b13002_013,True,1168,0.6,Now Married (Including Separated And Spouse Ab...
539,b25063_003,True,2215,0.5,With Cash Rent - Less Than $100
541,b25063_004,True,1964,0.5,With Cash Rent - $100 To $149
149,b03002_010,True,1772,0.4,Two Or More Races - Two Races Including Some O...
162,b03002_016,True,1132,0.3,Hispanic Or Latino - Asian Alone
219,b07204_006,True,627,0.3,Same City Or Town - Different County (Same State)
252,b07204_017,True,581,0.3,Abroad 1 Year Ago - Puerto Rico
285,b08006_013,True,518,0.3,Public Transportation (Excluding Taxicab) - Fe...
322,b13002_004,True,386,0.2,Now Married (Including Separated And Spouse Ab...
164,b03002_017,True,392,0.1,Hispanic Or Latino - Native Hawaiian And Other...
255,b07204_018,True,92,0.0,Abroad 1 Year Ago - U.S. Island Areas

In [13]:
sd_pctvar.loc[(sd_pctvar['sig_dif']==True)&(sd_pctvar['percent'] >=10.0)].count()

variable         171
sig_dif          171
sig_dif_count    171
percent          171
label            171
dtype: int64

## Significant Difference by Table and Summary Level

In [14]:
gfilter='050'
print(sumlev_names[gfilter].upper())
sd_pcttabgeo_file=os.path.join('sumdata','sigdif_pct_tabgeo.tsv')
sd_pcttabgeo=pd.read_csv(sd_pcttabgeo_file,delimiter='\t',dtype={'sumlevel':str})
sd_pcttabgeo.loc[(sd_pcttabgeo['sig_dif']==True) & (sd_pcttabgeo['sumlevel']==gfilter)].sort_values(by='percent',ascending=False)

COUNTY

      table sumlevel sig_dif  sig_dif_count  percent
46   b01002      050    True           5189     53.7
832  b25077      050    True           1565     48.6
553  b23025      050    True          10703     47.5
590  b25002      050    True           4556     47.2
470  b19013      050    True           1294     40.2
92   b02001      050    True          12748     39.6
364  b14001      050    True          12071     37.5
9    b01001      050    True          57811     36.6
625  b25003      050    True           3325     34.4
129  b03002      050    True          22379     33.1
911  c17002      050    True           8294     32.2
170  b05002      050    True          15112     31.3
435  b19001      050    True          16671     30.5
746  b25064      050    True            933     29.0
662  b25010      050    True           2731     28.3
281  b11001      050    True           7892     27.2
398  b15002      050    True          28631     25.4
319  b13002      050    True          14889     24.3
205  b07204      050    True          13318     21.8
514  b19083      050    True            687     21.3
248  b08006      050    True          11394     20.8
711  b25063      050    True          15967     20.7
949  c24030      050    True          19311     20.7
795  b25070      050    True           6863     19.4
878  b26001      050    True            249      7.7

# Coeficient of Variation for Significant Variables

## General Share of Records

In [15]:
cv_total_file=os.path.join('sumdata','change_cv_total_grand.tsv')
cv_total=pd.read_csv(cv_total_file,delimiter='\t')
cv_total

  change_cv  change_cv_count  percent
0       low         10046353     91.9
1    medium           686375      6.3
2      high           198811      1.8

### Share by Summary Level

In [16]:
cv_geoshare_file=os.path.join('sumdata','change_cv_share_geo.tsv')
cv_geoshare=pd.read_csv(cv_geoshare_file,delimiter='\t',dtype={'sumlevel':str})
cv_geoshare['sumlevel']=cv_geoshare['sumlevel'].map(sumlev_names)
cv_geoshare.sort_values(by=['percent','change_cv_count'],ascending=False)

            sumlevel  change_cv_count  percent
7          Blk Group          3952314     36.2
6              Tract          2822174     25.8
18              ZCTA          1215977     11.1
5      County Subdiv          1131118     10.3
8              Place           847449      7.8
4             County           279300      2.6
17              PUMA           260775      2.4
15        Urban Area           193420      1.8
14              CBSA            86636      0.8
16         Cong Dist            61837      0.6
13  Tribal Blk Group            19238      0.2
10       Tribal Area            18013      0.2
12      Tribal Tract            14777      0.1
11     Tribal Subdiv            11988      0.1
3              State            11647      0.1
2           Division             2465      0.0
1             Region             1138      0.0
9          Cons City              983      0.0
0                 US              290      0.0

### Share by Table

In [17]:
cv_tabshare_file=os.path.join('sumdata','change_cv_share_tab.tsv')
cv_tabshare=pd.read_csv(cv_tabshare_file,delimiter='\t')
cv_tabshare['label']=cv_tabshare['table'].map(tab_names)
cv_tabshare.sort_values(by='percent',ascending=False)

,table,change_cv_count,percent,label
0,b01001,2262353,19.6,Sex By Age
10,b15002,1162736,10.1,Sex By Educational Attainment For The Populati...
24,c24030,1035052,9.0,Sex By Industry For The Civilian Employed Popu...
11,b19001,850261,7.4,Household Income In The Past 12 Months (In 201...
3,b03002,626660,5.4,Hispanic Or Latino Origin By Race
18,b25063,568913,4.9,Gross Rent
7,b11001,524814,4.5,Household Type (Including Living Alone)
14,b23025,501004,4.3,Employment Status For The Population 16 Years ...
23,c17002,440367,3.8,Ratio Of Income To Poverty Level In The Past 1...
2,b02001,406030,3.5,Race
4,b05002,386998,3.3,Place Of Birth By Nativity And Citizenship Status
8,b13002,346752,3.0,Women 15 To 50 Years Who Had A Birth In The Pa...
6,b08006,339638,2.9,Sex Of Workers By Means Of Transportation To Work
20,b25070,339409,2.9,Gross Rent As A Percentage Of Household Income...
5,b07204,336426,2.9,Geographical Mobility In The Past Year For Cur...
9,b14001,314233,2.7,School Enrollment By Level Of School For The P...
16,b25003,215219,1.9,Tenure
15,b25002,222413,1.9,Occupancy Status
17,b25010,195951,1.7,Average Household Size Of Occupied Housing Uni...
1,b01002,186897,1.6,Median Age By Sex
21,b25077,122125,1.1,Median Value (Dollars)
19,b25064,67998,0.6,Median Gross Rent (Dollars)
12,b19013,64315,0.6,Median Household Income In The Past 12 Months ...
13,b19083,30812,0.3,Gini Index Of Income Inequality
22,b26001,5364,0.0,Group Quarters Population

## CV by Summary Level

In [18]:
cv_pctgeo_file=os.path.join('sumdata','change_cv_pct_geo.tsv')
cv_pctgeo=pd.read_csv(cv_pctgeo_file,delimiter='\t',dtype={'sumlevel':str})
cv_pctgeo['sumlevel']=cv_pctgeo['sumlevel'].map(sumlev_names)
cv_pctgeo.loc[cv_pctgeo['change_cv'].isin(['medium','high'])].groupby(by='sumlevel').sum().sort_values('percent',ascending=False)

                   change_cv  change_cv_count  percent
sumlevel
US                mediumhigh              283     97.6
Region            mediumhigh             1040     91.4
Division          mediumhigh             2145     87.1
State             mediumhigh             8522     73.2
Cong Dist         mediumhigh            32243     52.1
Cons City         mediumhigh              460     46.8
CBSA              mediumhigh            35035     40.4
County            mediumhigh            94875     34.0
PUMA              mediumhigh            87671     33.6
Urban Area        mediumhigh            30554     15.8
Tribal Area       mediumhigh             1953     10.8
Place             mediumhigh            86964     10.3
County Subdiv     mediumhigh            99994      8.8
ZCTA              mediumhigh           106216      8.7
Tribal Tract      mediumhigh              993      6.7
Tract             mediumhigh           164658      5.9
Tribal Subdiv     mediumhigh              642      5.4
Tribal Blk Group  mediumhigh              875      4.5
Blk Group         mediumhigh           130063      3.3

## CV by Table

In [19]:
cv_pcttab_file=os.path.join('sumdata','change_cv_pct_tab.tsv')
cv_pcttab=pd.read_csv(cv_pcttab_file,delimiter='\t',dtype={'sumlevel':str})
cv_pcttab['label']=cv_pcttab['table'].map(tab_names)
cv_pcttab.loc[cv_pcttab['change_cv'].isin(['medium','high'])].groupby(by='table').sum().sort_values('percent',ascending=False)

,change_cv,change_cv_count,percent,label
table,,,,
b25077,mediumhigh,40735,33.4,Median Value (Dollars)Median Value (Dollars)
b25064,mediumhigh,15285,22.4,Median Gross Rent (Dollars)Median Gross Rent (...
b26001,mediumhigh,1031,19.3,Group Quarters PopulationGroup Quarters Popula...
b25002,mediumhigh,35466,16.0,Occupancy StatusOccupancy Status
b08006,mediumhigh,49984,14.8,Sex Of Workers By Means Of Transportation To W...
b05002,mediumhigh,56861,14.7,Place Of Birth By Nativity And Citizenship Sta...
b03002,mediumhigh,88268,14.1,Hispanic Or Latino Origin By RaceHispanic Or L...
b02001,mediumhigh,57107,14.0,RaceRace
b19013,mediumhigh,8730,13.6,Median Household Income In The Past 12 Months ...
b23025,mediumhigh,68288,13.6,Employment Status For The Population 16 Years ...
b14001,mediumhigh,41128,13.1,School Enrollment By Level Of School For The P...
b01002,mediumhigh,23820,12.8,Median Age By SexMedian Age By Sex
b25003,mediumhigh,26810,12.4,TenureTenure
b07204,mediumhigh,38046,11.3,Geographical Mobility In The Past Year For Cur...
b25063,mediumhigh,49456,8.7,Gross RentGross Rent
c17002,mediumhigh,36584,8.3,Ratio Of Income To Poverty Level In The Past 1...
b11001,mediumhigh,37959,7.2,Household Type (Including Living Alone)Househo...
b13002,mediumhigh,24113,7.0,Women 15 To 50 Years Who Had A Birth In The Pa...
b25010,mediumhigh,12466,6.3,Average Household Size Of Occupied Housing Uni...
b15002,mediumhigh,69132,5.9,Sex By Educational Attainment For The Populati...
b19001,mediumhigh,48117,5.7,Household Income In The Past 12 Months (In 201...
b01001,mediumhigh,126972,5.6,Sex By AgeSex By Age
b19083,mediumhigh,1347,4.4,Gini Index Of Income InequalityGini Index Of I...
c24030,mediumhigh,44340,4.2,Sex By Industry For The Civilian Employed Popu...
b25070,mediumhigh,10129,3.0,Gross Rent As A Percentage Of Household Income...

## CV by Type of Variable

In [20]:
cv_pctvtype_file=os.path.join('sumdata','change_cv_pct_vtype.tsv')
cv_pctvtype=pd.read_csv(cv_pctvtype_file,delimiter='\t')
cv_pctvtype

    vartype change_cv  change_cv_count  percent
0  estimate       low          8930243     93.5
1  estimate    medium           498287      5.2
2  estimate      high           121224      1.3
3   summary       low           565715     84.7
4   summary    medium            87210     13.1
5   summary      high            15173      2.3
6  universe       low           550395     77.1
7  universe    medium           100878     14.1
8  universe      high            62414      8.7

## CV by Variable

In [21]:
cv_pctvar_file=os.path.join('sumdata','change_cv_pct_var.tsv')
cv_pctvar=pd.read_csv(cv_pctvar_file,delimiter='\t')
cv_pctvar['label']=cv_pctvar['variable'].map(var_names_short)
cv_pctvar.loc[cv_pctvar['change_cv'].isin(['medium','high'])].groupby(
    by='variable').sum().sort_values('percent',ascending=False).head(n=20)

,change_cv,change_cv_count,percent,label
variable,,,,
b08006_010,mediumhigh,5688,51.5,Public Transportation (Excluding Taxicab) - Su...
b08006_011,mediumhigh,6928,48.9,Public Transportation (Excluding Taxicab) - Lo...
b05002_001,mediumhigh,23261,41.6,Total Population - Total Total Population - T...
b08006_012,mediumhigh,3975,37.9,Public Transportation (Excluding Taxicab) - Li...
b07204_001,mediumhigh,18715,35.4,Population 1 Year And Over In The United Stat...
b25077_001,mediumhigh,40735,33.4,Owner-Occupied Housing Units - Median Value (...
b14001_001,mediumhigh,16158,31.5,Population 3 Years And Over - Total Populatio...
b01001_001,mediumhigh,26016,27.8,Total Population - Total Total Population - T...
b03002_001,mediumhigh,26016,27.8,Total Population - Total Total Population - T...
b02001_001,mediumhigh,26016,27.8,Total Population - Total Total Population - T...
b05002_002,mediumhigh,12954,27.0,Total - NativeTotal - Native
b14001_010,mediumhigh,12490,25.6,Total - Not Enrolled In SchoolTotal - Not Enro...
b25064_001,mediumhigh,15285,22.4,Renter-Occupied Housing Units Paying Cash Ren...
c17002_001,mediumhigh,19398,21.7,Population For Whom Poverty Status Is Determi...
b08006_001,mediumhigh,10104,21.6,Workers 16 Years And Over - Total Workers 16 ...
b25002_001,mediumhigh,18092,21.5,Housing Units - Total Housing Units - Total
b07204_002,mediumhigh,8864,20.0,Total - Same House 1 Year AgoTotal - Same Hous...
b23025_001,mediumhigh,17038,19.7,Population 16 Years And Over - Total Populati...
b25063_023,mediumhigh,5229,19.7,"With Cash Rent: - $2,000 Or More With Cash R..."
b15002_001,mediumhigh,16958,19.5,Population 25 Years And Over - Total Populati...

In [22]:
cv_pctvar.loc[cv_pctvar['change_cv'].isin(['medium','high'])].groupby(by='variable').sum().sort_values(
    ['percent','change_cv_count'],ascending=False).tail(n=20)

,change_cv,change_cv_count,percent,label
variable,,,,
b13002_003,mediumhigh,168,1.1,Women Who Had A Birth In The Past 12 Months - ...
b08006_006,mediumhigh,156,1.1,Carpooled - In 3-Person CarpoolCarpooled - In ...
c24030_040,mediumhigh,123,1.1,Female - InformationFemale - Information
b07204_013,mediumhigh,78,1.1,Different State - MidwestDifferent State - Mid...
b07204_018,medium,1,1.1,Abroad 1 Year Ago - U.S. Island Areas
c17002_004,mediumhigh,385,1.0,Total - 1.00 To 1.24Total - 1.00 To 1.24
b01001_033,mediumhigh,168,1.0,Female - 21 YearsFemale - 21 Years
b13002_005,mediumhigh,132,1.0,Now Married (Including Separated And Spouse Ab...
b25070_007,mediumhigh,211,0.9,Total - 30.0 To 34.9 PercentTotal - 30.0 To 34...
b19001_010,mediumhigh,296,0.8,Total - $45 000 To $49 999Total - $45 000 To $...
b13002_013,medium,9,0.8,Now Married (Including Separated And Spouse Ab...
c24030_054,mediumhigh,236,0.8,Female - Other Services Except Public Administ...
c24030_028,mediumhigh,198,0.7,Male - Public AdministrationMale - Public Admi...
c24030_055,mediumhigh,166,0.6,Female - Public AdministrationFemale - Public ...
b25070_009,mediumhigh,160,0.6,Total - 40.0 To 49.9 PercentTotal - 40.0 To 49...
c24030_035,mediumhigh,61,0.6,Female - Wholesale TradeFemale - Wholesale Trade
c17002_007,mediumhigh,166,0.5,Total - 1.85 To 1.99Total - 1.85 To 1.99
c24030_027,mediumhigh,136,0.5,Male - Other Services Except Public Administra...
c24030_008,medium,118,0.5,Male - Wholesale Trade
b25070_008,mediumhigh,109,0.5,Total - 35.0 To 39.9 PercentTotal - 35.0 To 39...

In [23]:
grouped_df=cv_pctvar.loc[cv_pctvar['change_cv'].isin(['medium','high'])].groupby(by='variable').sum()
grouped_df.loc[grouped_df['percent']>=20.0].count()

change_cv          17
change_cv_count    17
percent            17
label              17
dtype: int64

## CV by Table and Summary Level

In [24]:
gfilter='050'
print(sumlev_names[gfilter].upper())
cv_pcttabgeo_file=os.path.join('sumdata','change_cv_pct_tabgeo.tsv')
cv_pcttabgeo=pd.read_csv(cv_pcttabgeo_file,delimiter='\t',dtype={'sumlevel':str})
cv_pcttabgeo['label']=cv_pcttabgeo['table'].map(tab_names)
cv_pcttabgeo.loc[(cv_pcttabgeo['change_cv'].isin(['medium','high'])) 
                 & (cv_pcttabgeo['sumlevel']==gfilter)].groupby(by=['table','sumlevel']).sum().sort_values('percent',ascending=False)

COUNTY

,,change_cv,change_cv_count,percent,label
table,sumlevel,,,,
b03002,050,mediumhigh,14295,63.9,Hispanic Or Latino Origin By RaceHispanic Or L...
b02001,050,mediumhigh,7146,56.0,RaceRace
b23025,050,mediumhigh,5781,54.0,Employment Status For The Population 16 Years ...
b01002,050,mediumhigh,2623,50.6,Median Age By SexMedian Age By Sex
b25002,050,mediumhigh,2282,50.1,Occupancy StatusOccupancy Status
b05002,050,mediumhigh,7019,46.4,Place Of Birth By Nativity And Citizenship Sta...
b25077,050,mediumhigh,712,45.5,Median Value (Dollars)Median Value (Dollars)
b01001,050,mediumhigh,24440,42.3,Sex By AgeSex By Age
b14001,050,mediumhigh,4963,41.2,School Enrollment By Level Of School For The P...
b25003,050,mediumhigh,1243,37.4,TenureTenure
c17002,050,mediumhigh,2859,34.4,Ratio Of Income To Poverty Level In The Past 1...
b19013,050,mediumhigh,431,33.3,Median Household Income In The Past 12 Months ...
b07204,050,mediumhigh,4001,30.1,Geographical Mobility In The Past Year For Cur...
b13002,050,mediumhigh,4386,29.4,Women 15 To 50 Years Who Had A Birth In The Pa...
b25064,050,mediumhigh,272,29.1,Median Gross Rent (Dollars)Median Gross Rent (...
b15002,050,mediumhigh,7844,27.4,Sex By Educational Attainment For The Populati...
b08006,050,mediumhigh,3032,26.6,Sex Of Workers By Means Of Transportation To W...
b11001,050,mediumhigh,1906,24.1,Household Type (Including Living Alone)Househo...
b19001,050,mediumhigh,3945,23.7,Household Income In The Past 12 Months (In 201...
b25063,050,mediumhigh,2963,18.6,Gross RentGross Rent
b25010,050,mediumhigh,468,17.2,Average Household Size Of Occupied Housing Uni...
c24030,050,mediumhigh,3248,16.8,Sex By Industry For The Civilian Employed Popu...
b26001,050,mediumhigh,33,13.2,Group Quarters PopulationGroup Quarters Popula...
b25070,050,mediumhigh,645,9.4,Gross Rent As A Percentage Of Household Income...
b19083,050,mediumhigh,43,6.2,Gini Index Of Income InequalityGini Index Of I...